# Generated by Django 5.2.3 on 2025-06-25 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, default=0, max_length=100000, null=True)),
                ('expense', models.IntegerField(blank=True, default=0, max_length=100000, null=True)),
                ('invoice', models.IntegerField(blank=True, default=0, max_length=100000, null=True)),
                ('profit_after_tax', models.IntegerField(blank=True, default=0, max_length=100000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
