# Generated by Django 5.2 on 2025-04-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=80, null=True)),
                ('service_description', models.CharField(blank=True, max_length=200, null=True)),
                ('service_icon', models.ImageField(upload_to='images/uploads/')),
            ],
        ),
    ]
