# Generated by Django 5.2 on 2025-04-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_link_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
